### ISSUE TITLE
When I try to add the plugin into the project, it comes up with this error. [issue]

### ISSUE THREAD

**Issue by Zycanion** [Valkarin1029/YHModAssistant#3]
Unable to load addon script from path: 'res://addons/YHModAssistant-main/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/YHModAssistant-main/plugin.cfg' to prevent further errors.

I've followed all of the steps accordingly, including adding Python to the system path, although the error above pops up when I try to add it to the program.

**Comment by Valkarin1029** [comment]
Did yo download from the releases tab. Making a git clone for some reason causes that issue
